name: bmi_calcur
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  hive: ^2.0.4
  hive_flutter: ^1.0.0

  intl: ^0.18.1
  firebase_core: ^2.20.0
  cloud_firestore:
  firebase_auth: ^4.8.0
  google_sign_in: ^6.1.5
  gauge_indicator: ^0.4.3
  get: 4.6.6
  smooth_page_indicator: ^1.1.0
  animated_toggle_switch: ^0.8.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.0
  build_runner:
  flutter_test: 
    sdk: flutter

flutter:
  assets: 
    - assets/images/
  fonts: 
    - family: NotoSansKR
      fonts: 
        - asset: fonts/NotoSansKR-Regular.otf
        - asset: fonts/NotoSansKR-Black.otf
        - asset: fonts/NotoSansKR-Bold.otf
          weight: 600
        - asset: fonts/NotoSansKR-Light.otf
        - asset: fonts/NotoSansKR-Medium.otf
        - asset: fonts/NotoSansKR-Thin.otf
  uses-material-design: true
  #generate: true

