// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQEULGc228F9F9CovChusIbJZwZRmGFT0',
    appId: '1:306086306239:web:b5a985f2d2d0a32683410a',
    messagingSenderId: '306086306239',
    projectId: 'bmi-diary-ebce4',
    authDomain: 'bmi-diary-ebce4.firebaseapp.com',
    storageBucket: 'bmi-diary-ebce4.appspot.com',
    measurementId: 'G-1884FCZQ64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn8KEI9bhsc3JdIqbIY4elYLdm6UJhuzs',
    appId: '1:306086306239:android:91ecc556591f5e2083410a',
    messagingSenderId: '306086306239',
    projectId: 'bmi-diary-ebce4',
    storageBucket: 'bmi-diary-ebce4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDulGheVWYB_yW8D-GHLAzWHZZ9Q7IJ9l0',
    appId: '1:306086306239:ios:570ae2e2e2b0a39b83410a',
    messagingSenderId: '306086306239',
    projectId: 'bmi-diary-ebce4',
    storageBucket: 'bmi-diary-ebce4.appspot.com',
    iosBundleId: 'com.example.bmiCalcur',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDulGheVWYB_yW8D-GHLAzWHZZ9Q7IJ9l0',
    appId: '1:306086306239:ios:45bd9047bee69bed83410a',
    messagingSenderId: '306086306239',
    projectId: 'bmi-diary-ebce4',
    storageBucket: 'bmi-diary-ebce4.appspot.com',
    iosBundleId: 'com.example.bmiCalcur.RunnerTests',
  );
}
